apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secrets
  namespace: discord-bot
type: Opaque
data:
  open_ai_api_key: c2stcHJvai1Wa2FadVQ1UE9sdmlLZElCNExHdFQzQmxia0ZKSkdsdFQzVDRueGJtdkxTS0tGR0Y=
  discord_bot_token: T0RRd01USXpNVFkwTkRVM05UWTJNakE1LkdSQUhQTC5kSExOeVRoSUk0Yi1lU3BSMTRNZ0ZFTGN1Um1oc3RMRHVhTjZCQQ==
