apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/md0/data
    server: 10.0.0.150
  persistentVolumeReclaimPolicy: Retain