apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-data
  namespace: lidarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: lidarr-data
  storageClassName: ""