repositories:
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
releases:
  - name: otel-collector
    chart: open-telemetry/opentelemetry-collector
    version: 0.172.0
    values:
      - values.yaml
