# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-west-1"

  default_tags {
    tags = {
      Environment = "dev"
      Project     = "homelab"
      Terraform   = "true"
      ManagedBy   = "Terragrunt"
    }
  }
}
