apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: radarr-data
  storageClassName: ""