apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  template:
    spec:
      containers:
      - env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: GITHUB_CLIENT_ID
              name: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: GITHUB_CLIENT_SECRET
              name: github-client-secret
        name: dex