apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: searxng-secrets
  namespace: searxng
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: searxng-secrets
    creationPolicy: Owner
  data:
  - secretKey: searxng-secret-key
    remoteRef:
      key: f8c7ed29-00d9-471c-8bb5-99fabd9269ce
