apiVersion: v1
kind: Service
metadata:
  name: ai-artifacts-site
  namespace: ai-artifacts-site
spec:
  selector:
    app: ai-artifacts-site
  ports:
    - name: http
      port: 80
      targetPort: http
