apiVersion: patches/v1
kind: Patch
metadata:
  name: rename-operator-secret
patch: |-
  - op: replace
    path: /metadata/name
    value: signoz-clickhouse-operator-old
target:
  kind: Secret
  name: signoz-clickhouse-operator
