---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cowlab
  namespace: default
spec:
  secretName: cowlab-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.cowlab.org"
  dnsNames:
    - "*.cowlab.org"
    - "cowlab.org"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cowlab
  namespace: argocd
spec:
  secretName: cowlab-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.cowlab.org"
  dnsNames:
    - "*.cowlab.org"
    - "cowlab.org"
