apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-data
  namespace: copyparty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-config
  namespace: copyparty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
