apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-media
  namespace: copyparty
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: copyparty-media
  storageClassName: ""
