apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: longhorn-backup-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID | replace "\n" "" | replace "\r" "" }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY | replace "\n" "" | replace "\r" "" }}'
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: 0f562a12-9a7d-4bf1-9a71-d447b1937a0a
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: 53bafbba-8103-4e5a-9713-7720f9e18cc8
