ingress:
  enabled: false

preUpgradeChecker:
  jobEnabled: false

defaultBackupStore:
  backupTarget: "s3://myles-homelab-backups@us-west-1/longhorn-backups/"
  backupTargetCredentialSecret: "longhorn-backup-secret"
  pollInterval: 300