apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui-secrets
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: open-webui-secrets
    creationPolicy: Owner
  data:
  - secretKey: secret-key
    remoteRef:
      key: b6c2ef23-0115-41da-b045-f59610782a5c
