apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-client-secret
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: argocd-client-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ARGOCD_CLIENT_SECRET: '{{ .ARGOCD_CLIENT_SECRET | replace "\n" "" | replace "\r" "" }}'
  data:
  - secretKey: ARGOCD_CLIENT_SECRET
    remoteRef:
      key: ccbcba88-dcfb-4ec4-8223-453dd5491d67
