apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  template:
    spec:
      containers:
      - name: dex
        env:
        - name: ARGOCD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: argocd-client-secret
              key: ARGOCD_CLIENT_SECRET