# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "myles-homelab-tfstate"
    encrypt      = true
    key          = "modules/signoz-dashboards/kubernetes-nodes/terraform.tfstate"
    region       = "us-west-1"
    use_lockfile = true
  }
}
