# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "kubernetes" {
  config_path    = "~/.kube/config"
  config_context = "default"
}
provider "helm" {
  kubernetes = {
    config_path    = "~/.kube/config"
    config_context = "default"
  }
}
