apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: sonarr-data
  storageClassName: ""