apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-client-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: argocd-secret
    creationPolicy: Merge  # Merge with the secret created by Helm
    template:
      engineVersion: v2
      data:
        oidc.sso.clientSecret: '{{ .ARGOCD_CLIENT_SECRET | replace "\n" "" | replace "\r" "" }}'
  data:
  - secretKey: ARGOCD_CLIENT_SECRET
    remoteRef:
      key: ccbcba88-dcfb-4ec4-8223-453dd5491d67
