installCRDs: true

certManager:
  enabled: false  # Disabled to avoid circular dependency with cert-manager
  addInjectorAnnotations: false
  cert:
    create: false
    issuerRef:
      group: cert-manager.io
      kind: "Issuer"
      name: "external-secrets-ca-issuer"


webhook:
  certManager:
    enabled: false  # Disabled to avoid circular dependency with cert-manager
    cert:
      create: false

      issuerRef:
        group: cert-manager.io
        kind: "Issuer"
        name: "external-secrets-ca-issuer"
      duration: "2160h"
      renewBefore: "720h"
  #(Related to a cert invalid webhook issue)
  lookaheadInterval: "210h"