apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-data-nfs
  namespace: qbittorrent
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.0.0.150
    path: /mnt/md0/data
