apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data-nfs
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Ti
