apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wireguard-config
  namespace: qbittorrent
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: wireguard-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        wg0.conf: "{{ .wgconfig }}"
  data:
  - secretKey: wgconfig
    remoteRef:
      key: 08101098-e81a-4641-9411-1957c2510c92
