apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: longhorn
