apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
