apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books
  namespace: calibre
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: calibre-books
  storageClassName: ""