apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clickhouse-operator

resources:
  - namespace.yaml
  - helm-chart.yaml
  - externalsecrets/clickhouse-operator-secret.yaml

patches:
  - target:
      kind: Secret
      name: clickhouse-operator-altinity-clickhouse-operator
    patch: |-
      - op: replace
        path: /metadata/name
        value: clickhouse-operator-altinity-clickhouse-operator-old
