apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signoz-clickhouse-admin-secret
  namespace: signoz
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: signoz-clickhouse-admin
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: fcda1b2b-2824-4cd9-b0a6-6d2e24ebcb96
  - secretKey: password
    remoteRef:
      key: bf6485a1-2ef7-4aed-a4eb-28ae2a9567e7
