apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signoz-clickhouse-operator-secret
  namespace: signoz
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: signoz-clickhouse-operator
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: username
    remoteRef:
      key: 3d294568-f7f8-4687-9165-e1d8afc46d8a
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: password
    remoteRef:
      key: bf6485a1-2ef7-4aed-a4eb-28ae2a9567e7
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
